### ISSUE TITLE
Old project from 2.5.0 engine, unable to start it on 3.0.0+

### ISSUE THREAD

**Issue by zigavr11** [WaveEngine/Feedback#74]
*Tried to sent this through contact but it doesn't work*
Hello,

I have a project that is around 5 years old. In the nuget packages it writes that it uses the 2.5.0 wavengine version. 
Right now I have 3.0.0 version installed and if I try to open the project I get an error:  TheProject: /.../ can not be opened. Object reference not set to an instance of an object.
If I try to compile the visual studio solution I get this error: The specified task executable "cmd.exe" could not be run. The working directory "v2.0\Tools\VisualEditor\" does not exist.

So I would like to know if there is any solution for this problem? I hoped that maybe you would be able to sent me a 2.5.0 wave engine version?

Thank you

Ziga

**Comment by illanos** [comment]
Hi @zigavr11, 2.5.0 version requieres a 2.5 installer,  the old installer is still available at the bottom of the downloads section
https://waveengine.net/Downloads

Here is a direct link
https://waveenginefiles.blob.core.windows.net/installers/WaveEngineSetup_2_5_0.exe

I hope this solves your problem.
We also recomend you to migrate to wave 3.1 and see the improvements of the new Editor and features.

Have a nice day.

**Comment by zigavr11** [comment]
Hello,

Thank you for the link.
I did want to migrate it to 3.1 but I am getting the above errors. 
I literally cannot open my project in wave engine, because of the above error.

Thank you

**Comment by illanos** [comment]
Hi @zigavr11 ! let me see if I get this clear, you install this app, https://waveenginefiles.blob.core.windows.net/installers/WaveEngineSetup_2_5_0.exe , and open de proyect with this version of the engine, shows the error?

```
TheProject: /.../ can not be opened. Object reference not set to an instance of an object.
If I try to compile the visual studio solution I get this error: The specified task executable "cmd.exe" could not be run. The working directory "v2.0\Tools\VisualEditor" does not exist.
```

If this is the case, can you check that v2.0\Tools\VisualEditor (in the wave install directory) is not Empty?

In other case, If you open the proyect  2.5 with the new version of the editor (3.0 or above), I am afraid the version is not compatible with 2.5 and you have to migrate it by redoing the whole proyect again because there are so many breaking changes that will be the easiest way.

Hope this helps.

**Comment by zigavr11** [comment]
> Hi @zigar, I am afraid that wave engine 3.0 is not retrocompatible with older versions of the engine, there are too many braking changes and it is not possible to open a 2.5 version with 3.0 and we recomend you to create this proyect from scratch.
> 
> Sorry for that.
> 
> You can still acces to your 2.5 version by installing this app and open it with this version
> https://waveenginefiles.blob.core.windows.net/installers/WaveEngineSetup_2_5_0.exe
> 
> Hope this helps.

Okay thank you.
