### ISSUE TITLE
Custom namespaces

### ISSUE THREAD

**Issue by BChapoulie** [WaveEngine/Feedback#79]
Hi, 

I am developping a solution for a company and to follow the convention I'd like to name my project and have namespaces following the given schema: [Company name].[Project name].
However I can't create a project which name contains a dot in it. I've tried to change the assemblies and namespaces after the creation myself but I don't manage to make it work properly (issue with code generation for scenes at first and then issue with the Editor... even after deletion of it or renaming).
I've search some variables I can set for the .targets but I didn't find anything that seemed to get to what I want.
Is there any possibility to achieve my goal?

Thanks for your help.

**Comment by danielcaceresm** [comment]
Hi @BChapoulie ! 

Sorry for the delay. 
You can change the namespace of all existing types, and customize the default namespace for the project. Also you can change the assembly name:
````
    <RootNamespace>MyWaveProject.Gh79</RootNamespace>
    <AssemblyName>MyWaveProject.Gh79</AssemblyName> 
````
Sadly, this is not possible now using the versions 3.2.0.7765-preview and 3.2.0.7787-preview, because there is a bug in the package WaveEngine.CodeScene. I have just tested with our last nightly build and it is fixed. We will release a new preview build soon.

The only thing you cannot modify is the name of the projects. As you have indicated the targets use it in a way that must be fixed. We have this bug in our backlog, but I don't know when it will be addressed.

Sorry for the inconvenience.

**Comment by BChapoulie** [comment]
Hi, 

Thanks for your reply. 
The namespace and assembly name aren't really an issue in itself, just I will not follow the company conventions for now. I will keep looking on the updates to see if I can achieve this goal and will not miss to keep this issue updated.

**Comment by danielcaceresm** [comment]
Hi @BChapoulie,

The las release (3.3.0.8524-preview) allows to create projects with name containing dots.
I will close the issue, feel free to reopen it if you need.
