### ISSUE TITLE
Problem building an empty project on WaveEngine 3.2

### ISSUE THREAD

**Issue by ebfortin** [WaveEngine/Feedback#80]
I used "Create Project" within WaveEngine 3.2 and  didn't add anything to it. When the project is opened it restore some packages and try to build. That's when it fails with : 

\MyWaveProject\MyWaveProject.Editor\MyWaveProject.Editor.csproj : error MSB4057: The target "MyWaveProject_Editor" does not exist in the project.

I'm totally new to WaveEngine but not to .NET programming. I don't get that error.

I've created  DirectX11 Windows project.

**Comment by ebfortin** [comment]
I can also add that it builds OK in Visual Studio.

**Comment by minolo** [comment]
Hi there.

Could you tell me the exact version you're using for this?

Thanks!

**Comment by BChapoulie** [comment]
Hello,

I have the exact same problem using the version 3.2.7787-preview. I was working on VisualStudio so I didn't notice the problem until I wanted to change a few things with the WaveEngine editor. I checked and I have the same issue with an empty project. So it doesn't come from the modifications I've made.

Thanks for your help.

**Comment by BChapoulie** [comment]
Little update on that, I've tried to create a new project with WaveEngine 3.1.0.6798-preview2 and have the exact same problem on an empty project. Could it come from a malfunction in the new version of the editor and not from the framework?

**Comment by minolo** [comment]
Hi there! Sorry for the delay.

It seems that the problem lies in the build tools. There was [a bug in the MSBuild tool](https://github.com/dotnet/msbuild/issues/6373) which caused this issue.

You were probably using Visual Studio version 16.10, which presents this error. They've just released version 16.10.1 which fixes this issue, so try updating to the new version. The problem should be gone.

In addition, if you have the Preview version installed, this might not solve the issue, as the Preview version probably doesn't have that fix yet, and WaveEngine's build scripts select the latest version of the tools to compile. Tell me if that's your case so I can get a workaround for you.

I hope this helps you!

**Comment by BChapoulie** [comment]
Hello,

Thank you very much for your reply. The problem was indeed with the version of VisualStudio because I was using the version 16.10. Updating to the just released new version solved my issue! 😄
