### ISSUE TITLE
Deferred render

### ISSUE THREAD

**Issue by Hromon** [WaveEngine/Feedback#92]
Are you planning to add deferred render to the engine?

**Comment by minolo** [comment]
Hi there!

We do not have that feature planned in our roadmap for the near future. However, the current render architecture has the flexibility to allow making a custom RenderPath which implements Deferred Rendering.

For now we are giving higher priority to techniques related to Forward Rendering due to their better performance in VR and MR applications, as well as possible future optimizations like Forward+.

I hope to have been helpful.
